FROM jenkins/jenkins:lts-jdk17

USER root

# ==========================================
# Install base dependencies + Python + Node.js
# ==========================================
RUN apt-get update && \
    apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    python3 \
    python3-pip \
    python3-venv \
    nodejs \
    npm && \
    install -m 0755 -d /etc/apt/keyrings

# ==========================================
# Install Docker CLI
# ==========================================
RUN curl -fsSL https://download.docker.com/linux/debian/gpg \
    -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli

# ==========================================
# Install kubectl
# ==========================================
RUN curl -LO "https://dl.k8s.io/release/v1.34.1/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# ==========================================
# Install Trivy
# ==========================================
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
    sh -s -- -b /usr/local/bin

# ==========================================
# Install pytest
# ==========================================
RUN pip3 install --break-system-packages pytest

# ==========================================
# Cleanup
# ==========================================
RUN rm -rf /var/lib/apt/lists/*

USER jenkins