apiVersion: v1
kind: Service

metadata:
  name: enterprise-platform-service

spec:

  type: {{ .Values.service.type }}

  selector:
    app: enterprise-platform

  ports:

  - port: {{ .Values.service.port }}

    targetPort: 5000