apiVersion: v1
kind: Service

metadata:
  name: enterprise-platform-service
  namespace: enterprise-devops

spec:
  selector:
    app: enterprise-platform

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer