apiVersion: v1
kind: ConfigMap

metadata:
  name: enterprise-config
  namespace: enterprise-devops

data:
  ADMIN_USERNAME: admin
  POSTGRES_DB: enterprise_db
  POSTGRES_USER: enterprise_user
  POSTGRES_HOST: enterprise-postgres
  POSTGRES_PORT: "5432"