apiVersion: v1
kind: Service

metadata:
  name: enterprise-postgres
  namespace: enterprise-devops

spec:
  selector:
    app: enterprise-postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP