apiVersion: v1
kind: Secret

metadata:
  name: enterprise-secret
  namespace: enterprise-devops

type: Opaque

stringData:
  SECRET_KEY: "CHANGE_ME"
  ADMIN_PASSWORD: "CHANGE_ME"
  POSTGRES_PASSWORD: "CHANGE_ME"
  DATABASE_URL: "postgresql://enterprise_user:CHANGE_ME@enterprise-postgres:5432/enterprise_db"