apiVersion: v1
kind: Secret

metadata:
  name: enterprise-secret
  namespace: enterprise-devops

type: Opaque

stringData:
  SECRET_KEY: MySuperSecretKey2026
  ADMIN_PASSWORD: Admin123!
  POSTGRES_PASSWORD: enterprise_password
  DATABASE_URL: postgresql://enterprise_user:enterprise_password@enterprise-postgres:5432/enterprise_db