apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-platform
  namespace: enterprise-prod

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: enterprise-platform

  template:
    metadata:
      labels:
        app: enterprise-platform
        environment: prod

    spec:
      containers:
        - name: enterprise-platform
          image: 519747128244.dkr.ecr.us-east-1.amazonaws.com/enterprise-devops-platform:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /login
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /login
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3