apiVersion: v1
kind: Service

metadata:
  name: enterprise-platform-service
  namespace: enterprise-devops

spec:
  selector:
    app: enterprise-platform

  ports:
  - port: 5000
    targetPort: 5000

  type: NodePort